spring.application.name=web
spring.h2.console.enabled=true

# Database Connection Settings
spring.datasource.url=jdbc:h2:file:./data/sampleDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update